defaults:
  - rendering_base
  - _self_

integrator: nerad_sg
config:
  hide_emitters: true
  return_depth: false
  max_depth: 22
  rr_depth: 5
  second_residual: true

post_init:
  # override in child config
  function:
  kwargs: {}
  # auto set
  residual_function:
